name: CI/CD for Dev

on:
  push:
    branches: [dev]

jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo " Dev test complete"

    - name: Auto-merge to main
      uses: devops-infra/action-pull-request@v0.5.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: dev
        target_branch: main
        title: "Auto-merge: Dev → Main"
        body: "Merging dev into main after successful CI"
