name: Post-Merge Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to Render
        if: success()
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$DEPLOY_HOOK" ]; then
            echo "🔒 RENDER_DEPLOY_HOOK not set — skipping deploy."
          else
            curl -X POST $DEPLOY_HOOK
            echo "Deployment triggered on Render"
          fi
